### ISSUE TITLE
Add clippy to CI

### ISSUE THREAD

**Issue by gussmith23** [gussmith23/glenside#169]
Run `cargo clippy` in CI and fail on warnings.

**Comment by RishiKumarRay** [comment]
@gussmith23  can you give any example , I understood the clippy part but how to fail on warnings

**Comment by gussmith23** [comment]
it may be enough to just run "cargo clippy". I want CI to fail if clippy throws any warnings, but we can start by just running clippy in CI!

**Comment by RishiKumarRay** [comment]
@gussmith23 In which file do you want to add or else should i go for new Yaml file?

**Comment by gussmith23** [comment]
a new file should be great, you can copy the rustfmt file!

**Comment by RishiKumarRay** [comment]
@gussmith23 can you please check this? https://github.com/RishiKumarRay/glenside/commit/76dc0c688e221d57cea6c6648be4a676bfb06434

**Comment by gussmith23** [comment]
Can you open a pull request?

**Comment by RishiKumarRay** [comment]
@gussmith23 yeah i have created it please do check
