### ISSUE TITLE
Benchmark interpreter so that we can measure improvement

### ISSUE THREAD

**Issue by gussmith23** [gussmith23/glenside#33]

**Comment by gussmith23** [comment]
@hypercubestart I think this is the right place to start. Partly because it's the first thing we need to do to improve the interpreter, but also because it will get you acquainted with the interpreter, and involves utilizing a feature of Rust/Cargo (one that I've never actually used, so you might have to explain it to me...)

Here's what I suggest:
1. Take a look at/run the [interpreter tests (bottom of the file).](https://github.com/gussmith23/glenside/blob/master/src/language/interpreter_new.rs).
2. Read up on Rust's [benchmark tests](https://doc.rust-lang.org/1.7.0/book/benchmark-tests.html)
3. See if you can modify the interpreter tests to be benchmarks as well! Or, maybe we need to create separate benchmark tests. Unsure -- let me know what you think

**Comment by gussmith23** [comment]
While you're working on this one, you might also want to think about #26 -- you might come up with a clever way to use Rust macros to rewrite the tests compactly. See that issue for more notes.

**Comment by hypercubestart** [comment]
@gussmith23 benchmarking is an unstable feature in Rust. I think if we want benchmarking, we need to use the nightly build of Rust and compile with `-Z unstable-options` falg

**Comment by gussmith23** [comment]
yes! I think I'm actually already using nightly rust on my machine actually. it seems like using nightly is super common in the rust world... I'd honestly say I see more people talking about using nightly than stable
